### ISSUE TITLE
When an error occurs with the call, every subsequent request is the same error

### ISSUE THREAD

**Issue by beausoft** [traverson/traverson-hal#36]
When an error occurs on a request, every subsequent request is the error 
Error: Could not find a matching link nor an embedded document for

**Comment by basti1302** [comment]
Please provide an actual code snippet that shows how you are
- initialising traverson and traverson-hal
- calling traverson (the full call chain starting at `traverson.from(...)`)
- where you encounter the first error
- what you mean by subsequent requests

An [SCCEE](http://sscce.org/) would be even better.

Thanks in advance.

**Comment by beausoft** [comment]
Thanks Call again at `traverson.from(...)` resolved the issues
