### ISSUE TITLE
.follow() problem

### ISSUE THREAD

**Issue by keawest** [traverson/traverson-hal#70]
Hi! I'm trying to follow a bunch of links from the rootUrl but I just can't seem to get it working properly, I am quite new to this but have read all the documentation and can't find out what the problem is. I hope the pictures below explain my problem.

This is the root resource in my case, to start with i'm trying to navigate to one or both of the url's in "basisgruppe":
![Skjermbilde 2021-03-12 132223](https://user-images.githubusercontent.com/42249819/110942602-5017a200-833a-11eb-9ec5-47f3e4502578.png)

**To Reproduce**
1. I am using the following Traverson call (please provide the full code snippet and also how you initialize `traverson` and `traverson-hal`) '...'
![Skjermbilde 2021-03-12 135201](https://user-images.githubusercontent.com/42249819/110942675-6de50700-833a-11eb-887c-447e97cfb828.png)

**Node.js (please complete the following information):**
 - OS: Windows 10
 - Node.js version: v14.16.0.
 - Traverson Version: 7.0.1
 - Traverson Hal Version: 7.0.2

**Additional context**

I am wondering if the problem could be that the url for "basisgruppe" is inside an array or maybe the problem is with the entire thing being "_embedded"?
Any help with this would be much appreciated since this is an assignment during my internship :)

**Comment by basti1302** [comment]
Hey there!

First of all, what is the output that you are getting? An error message or anything?

Second, it has really been a long while since I last worked with this, so I can't say what the correct path is just from eyeballing your screenshots. I think you need to include `_entries` and possibly the index into the `_entries` array in the parameters provided to the `follow` method - see https://github.com/traverson/traverson-hal#selecting-from-a-collection-of-embedded-resources. If you always want the first `_entries` object, you can omit the index.

Can you give `.follow(`_entries`, `basisgruppe`)  a try? (leaving the rest of your code unchanged). No guarantees though that this will work. 

If you 

1. could post your root resource _and_ your code as actual text (instead of screenshots) and
2. provide the error message or unexpected outcome that you are getting, 

then I would be willing to reproduce this locally to help you with the correct arguments. But I am not willing to transcribe that from your screenshots ;-)  

Good luck with your internship :)

**Comment by keawest** [comment]
Thank you for the quick answer and sorry for only providing screenshots!
I have had some progress since my last post but not quite there yet.. 

Using your tips and the following as root url I am now able to follow the link to "elev", but if I try to follow both "elev" and "skole" as in the code snippet I get the HalError:

```HalLinkError: Could not find a matching link nor an embedded document for _entries[1].```

I need to follow both these links because they will tell me which students are enrolled at what school etc.
I will also need to fetch the information from other links on this root url, like "basisgruppe" and maybe "undervisningsgruppe" but if i can get "elev" and "skole" the rest should not be a problem, right? 

Any input would be awesome :D

```
{
    _embedded: {
        _entries: [
            {
                beskrivelse: "",
                systemId: {
                    identifikatorverdi: "*******"
                },
                _links: {
                    elev: [
                        {
                            href: "https://beta.felleskomponent.no/utdanning/elev/elev/systemid/"
                        }
                    ],
                    skole: [
                        {
                            href: "https://beta.felleskomponent.no/utdanning/utdanningsprogram/skole/systemid/"
                        }
                    ],
                    undervisningsgruppe: [
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        },
                        {
                            href: "https://beta.felleskomponent.no/utdanning/timeplan/undervisningsgruppe/systemid/"
                        }
                    ],
                    basisgruppe: [
                        {
                            href: "https://beta.felleskomponent.no/utdanning/elev/basisgruppe/systemid/"
                        }
                    ],
                    kontaktlarergruppe: [
                        {
                            href: "https://beta.felleskomponent.no/utdanning/elev/kontaktlarergruppe/systemid/"
                        }
                    ],
                    kategori: [
                        {
                            href: "https://beta.felleskomponent.no/utdanning/kodeverk/elevkategori/systemid/heltid"
                        }
                    ],
                    self: [
                        {
                            href: "https://beta.felleskomponent.no/utdanning/elev/elevforhold/systemid/"
                        }
                    ]
                }
            }
        ]
    }
}
```

```
    traverson
        .from('https://beta.felleskomponent.no/utdanning/elev/elevforhold')
        .withRequestOptions({
            headers: {
                Authorization: `Bearer ${user.accessToken}`
            }
        })
        .jsonHal()
        .follow('_entries[0]', 'elev').follow('_entries[1]', 'skole')
        .getResource(function (error, resource) {
            if (error) { console.log(error + 'no luck..') }
            console.log(resource)
        })

```

**Comment by keawest** [comment]
Nevermind! I think that I just got it working as it should :)
My working code looks something like this:

```
    traverson
        .from('https://beta.felleskomponent.no/utdanning/elev/elevforhold')
        .withRequestOptions({
            headers: {
                Authorization: `Bearer ${user.accessToken}`
            }
        })
        .jsonHal()
        .follow('_entries', 'elev')
        .getResource(function (error, doc, traversal) {
            if (error) { console.log(error) }
            console.log('elevnummer: ' + doc.elevnummer.identifikatorverdi)
            console.log('Epostadresse: ' + doc.kontaktinformasjon.epostadresse)

            traversal
                .continue()
                .follow('elevforhold', 'elev', 'person')
                .getResource(function (error, doc2, traversal2) {
                    if (error) { console.log(error) }
                    console.log('navn: ' + doc2.navn.fornavn, doc2.navn.etternavn)

                    traversal2
                        .continue()
                        .follow('elev', 'elevforhold', 'basisgruppe')
                        .getResource(function (error, doc3, traversal3) {
                            if (error) { console.log(error) }
                            console.log('basisgruppe: ' + doc3.beskrivelse)
                            console.log('basisgruppe identifikatorverdi: ' + doc3.systemId.identifikatorverdi)

                            traversal3
                                .continue()
                                .follow('skole')
                                .getResource(function (error, doc4, traversal4) {
                                    if (error) { console.log(error) }
                                    console.log('skole: ' + doc4.navn)
                                    console.log('skolenummer: ' + doc4.skolenummer.identifikatorverdi)
                                })
                        })
                })
        })

```


Probably not the prettiest creation ever but it fetches the information that I was looking for. If you see any obvious problems with my code or any ways it could have been simplified i please share, otherwise I guess the issue should be closed.

**Comment by basti1302** [comment]
I think

```
.from('https://beta.felleskomponent.no/utdanning/elev/elevforhold').follow('_entries', 'elev', 'elevforhold', 'elev', 'person', 'elev', 'elevforhold', 'basisgruppe', 'skole')
```

should give you the same result as stopping the traversal and then continuing it a bunch of times.

**Comment by keawest** [comment]
I tried your code but then I only got the results from the last resource eg. "skole", is there a way besides the one I posted, of accessing the data from the other resources as well?

I am currently gathering data like:
- personal info from "elev"
- which classes they are enrolled in from "elevforhold"
- what school they go to from "skole"

since "skole" does not hold all the data I need

**Comment by basti1302** [comment]
I see. When you need data from the resources you encounter along the way, then your approach is exactly right. That's what the `.continue` method is there for.

Nice that it worked out for you.
